# Generated by Django 5.2.9 on 2025-12-11 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance_z', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit UZS'), ('convert_to_z', 'Convert to Z coins'), ('course_purchase', 'Course purchase'), ('tournament_fee', 'Tournament fee'), ('prize', 'Prize'), ('withdraw', 'Withdraw'), ('referral_bonus', 'Referral bonus')], max_length=50)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_z', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
